name: Build Android .so

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up NDK
      run: echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/26.1.10909125" >> $GITHUB_ENV

    - name: Download Dear ImGui
      run: |
        curl -sL https://github.com/ocornut/imgui/archive/refs/tags/v1.90.1.zip -o imgui.zip
        unzip -q imgui.zip
        mv imgui-1.90.1/* .

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake" \
              -DANDROID_ABI=armeabi-v7a \
              -DANDROID_PLATFORM=android-21 \
              ..

    - name: Build project
      run: |
        cd build
        make

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled-so-file
        path: build/*.so
